<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIyUcP9u\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIyUcP9u/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerIyUcP9u.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerIyUcP9u\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerIyUcP9u\appAppKernelProdContainer([
    'container.build_hash' => 'IyUcP9u',
    'container.build_id' => 'c91493cd',
    'container.build_time' => 1734792702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIyUcP9u');
